on:
  push:
    branches:
      - master

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.6'
          spec: 'main.py'
          upload_exe_with_name: 'Downloader'
          options: --onefile, --name "Downloader", --windowed, 
